baseURL = "https://chenatu.github.io/"
title   = "Tech Notes"
languageCode = "en-us"


[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  defaultTheme = "auto"        # è·Ÿéšç³»ç»Ÿæ·±æµ…è‰²
  showCodeCopyButtons = true   # ä»£ç å—ä¸€é”®å¤åˆ¶
  comments = true
[params.giscus]
  repo = "chenatu/chenatu.github.io"
  repo_id = "R_kgDOPVGbaQ"        # 4 ä¸ª *ID* æºè‡ª giscus.app
  category = "Comments"
  category_id = "DIC_kwDOPVGbac4CtkYf"
  mapping = "pathname"
  reactions_enabled = "1"          # æ˜¾ç¤º ğŸ‘ğŸ˜‚ğŸ‰ â€¦
  emit_metadata   = "0"
  input_position  = "bottom"
  theme           = "preferred_color_scheme"
  lang            = "zh-CN"


[markup]
  [markup.highlight]
    style = "dracula"          # ç¨‹åºå‘˜å‹å¥½çš„é«˜å¯¹æ¯”é…è‰²


